[pytest]
DJANGO_SETTINGS_MODULE = config.settings.local
python_files = tests.py test_*.py *_tests.py
addopts = --strict-markers --no-migrations --tb=short
markers =
    unit: Unit tests
    integration: Integration tests
    api: API endpoint tests
