# Generated by Django 5.0.7 on 2026-08-01 11:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(db_index=True, max_length=255)),
                ("legal_business_name", models.CharField(max_length=255)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("SOLE_PROPRIETORSHIP", "Sole Proprietorship"),
                            ("PARTNERSHIP", "Partnership"),
                            ("PRIVATE_LIMITED", "Private Limited"),
                            ("PUBLIC_LIMITED", "Public Limited"),
                            ("LLP", "Limited Liability Partnership"),
                        ],
                        default="INDIVIDUAL",
                        max_length=50,
                    ),
                ),
                (
                    "merchant_category_code",
                    models.CharField(default="5734", max_length=10),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=15, null=True
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("support_email", models.EmailField(max_length=254)),
                ("support_phone", models.CharField(max_length=20)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("address", models.TextField()),
                ("country", models.CharField(default="IN", max_length=3)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Profile",
                "verbose_name_plural": "Merchant Profiles",
                "db_table": "merchant_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantAPIKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Default Live Key", max_length=100)),
                (
                    "publishable_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "hashed_secret_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("secret_key_prefix", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="merchant.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "merchant_api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantWebhookSecret",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret_prefix", models.CharField(max_length=16)),
                ("hashed_secret", models.CharField(max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_secret",
                        to="merchant.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "merchant_webhook_secrets",
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enabled_events", models.JSONField(default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_webhook_configs",
                        to="merchant.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "merchant_webhook_endpoints",
                "ordering": ["-created_at"],
            },
        ),
    ]
