import uuid

from common.models import SoftDeleteModel, TimeStampedModel
from customer.models import CustomerProfile
from django.db import models
from merchant.models import MerchantProfile


class OrderStatus(models.TextChoices):
    DRAFT = "DRAFT", "Draft"
    PENDING = "PENDING", "Pending"
    PROCESSING = "PROCESSING", "Processing"
    PAID = "PAID", "Paid"
    FAILED = "FAILED", "Failed"
    CANCELLED = "CANCELLED", "Cancelled"
    EXPIRED = "EXPIRED", "Expired"
    REFUNDED = "REFUNDED", "Refunded"


class Order(TimeStampedModel, SoftDeleteModel):
    """
    Order Entity representing payment request contracts generated by Merchants.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    order_number = models.CharField(
        max_length=100, unique=True, db_index=True
    )  # ord_xxxx
    merchant = models.ForeignKey(
        MerchantProfile, on_delete=models.CASCADE, related_name="orders", db_index=True
    )
    customer = models.ForeignKey(
        CustomerProfile,
        on_delete=models.SET_NULL,
        related_name="orders",
        null=True,
        blank=True,
        db_index=True,
    )
    amount = models.DecimalField(max_digits=12, decimal_places=2, db_index=True)
    currency = models.CharField(max_length=3, default="INR", db_index=True)
    description = models.TextField(blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    status = models.CharField(
        max_length=20,
        choices=OrderStatus.choices,
        default=OrderStatus.PENDING,
        db_index=True,
    )
    expires_at = models.DateTimeField(null=True, blank=True, db_index=True)
    created_by = models.CharField(max_length=100, blank=True)
    updated_by = models.CharField(max_length=100, blank=True)

    class Meta:
        db_table = "orders"
        verbose_name = "Order"
        verbose_name_plural = "Orders"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["merchant", "status", "created_at"]),
            models.Index(fields=["customer", "status"]),
            models.Index(fields=["status", "expires_at"]),
        ]

    def __str__(self):
        return f"{self.order_number} - {self.amount} {self.currency} [{self.status}]"


class OrderEventType(models.TextChoices):
    CREATED = "order.created", "Order Created"
    UPDATED = "order.updated", "Order Updated"
    CANCELLED = "order.cancelled", "Order Cancelled"
    EXPIRED = "order.expired", "Order Expired"
    PAID = "order.paid", "Order Paid"


class OrderEvent(TimeStampedModel):
    """
    Domain Event Log tracking all state mutations and events for an Order.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="events", db_index=True
    )
    event_type = models.CharField(
        max_length=50, choices=OrderEventType.choices, db_index=True
    )
    payload = models.JSONField(default=dict)

    class Meta:
        db_table = "order_events"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.event_type} -> {self.order.order_number}"


class CouponDiscountType(models.TextChoices):
    PERCENTAGE = "PERCENTAGE", "Percentage"
    FIXED = "FIXED", "Fixed Amount"


class CouponStatus(models.TextChoices):
    ACTIVE = "ACTIVE", "Active"
    EXPIRED = "EXPIRED", "Expired"
    DISABLED = "DISABLED", "Disabled"


class Coupon(TimeStampedModel):
    """
    Discount Coupon Model.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    code = models.CharField(max_length=50, unique=True, db_index=True)  # e.g., SAVE20
    merchant = models.ForeignKey(
        MerchantProfile, on_delete=models.CASCADE, related_name="coupons", db_index=True
    )
    discount_type = models.CharField(
        max_length=20,
        choices=CouponDiscountType.choices,
        default=CouponDiscountType.PERCENTAGE,
    )
    discount_value = models.DecimalField(max_digits=12, decimal_places=2)
    max_discount_amount = models.DecimalField(
        max_digits=12, decimal_places=2, null=True, blank=True
    )
    min_order_amount = models.DecimalField(
        max_digits=12, decimal_places=2, default=0.00
    )
    usage_limit = models.IntegerField(default=100)
    used_count = models.IntegerField(default=0)
    status = models.CharField(
        max_length=20,
        choices=CouponStatus.choices,
        default=CouponStatus.ACTIVE,
        db_index=True,
    )

    class Meta:
        db_table = "coupons"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Coupon: {self.code} [{self.discount_type}]"


class InvoiceStatus(models.TextChoices):
    ISSUED = "ISSUED", "Issued"
    PAID = "PAID", "Paid"
    CANCELLED = "CANCELLED", "Cancelled"


class Invoice(TimeStampedModel):
    """
    PDF Invoice Entity representing generated financial statements for Orders.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    invoice_number = models.CharField(
        max_length=100, unique=True, db_index=True
    )  # inv_xxxx
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="invoices", db_index=True
    )
    merchant = models.ForeignKey(
        MerchantProfile,
        on_delete=models.CASCADE,
        related_name="invoices",
        db_index=True,
    )
    customer = models.ForeignKey(
        CustomerProfile,
        on_delete=models.SET_NULL,
        related_name="invoices",
        null=True,
        blank=True,
    )
    subtotal = models.DecimalField(max_digits=12, decimal_places=2)
    discount_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    tax_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    total_amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=3, default="INR")
    status = models.CharField(
        max_length=20,
        choices=InvoiceStatus.choices,
        default=InvoiceStatus.ISSUED,
        db_index=True,
    )
    pdf_file_path = models.CharField(max_length=500, blank=True)

    class Meta:
        db_table = "invoices"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.invoice_number} -> {self.total_amount} {self.currency} [{self.status}]"
