# Generated by Django 5.0.7 on 2026-08-01 11:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("merchant", "0001_initial"),
        ("orders", "0001_initial"),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("DUMMY", "Dummy Gateway"),
                            ("STRIPE", "Stripe Gateway"),
                            ("RAZORPAY", "Razorpay Gateway"),
                            ("WALLET", "Digital Wallet"),
                            ("COD", "Cash On Delivery"),
                        ],
                        db_index=True,
                        default="DUMMY",
                        max_length=50,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "amount",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(db_index=True, default="INR", max_length=3),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CARD", "Card"),
                            ("UPI", "UPI"),
                            ("NETBANKING", "Net Banking"),
                            ("WALLET", "Wallet"),
                            ("COD", "Cash On Delivery"),
                        ],
                        db_index=True,
                        default="CARD",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("AUTHORIZED", "Authorized"),
                            ("CAPTURED", "Captured"),
                            ("SETTLED", "Settled"),
                            ("FAILED", "Failed"),
                            ("VOIDED", "Voided"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=50)),
                ("failure_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="customer.customerprofile",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="merchant.merchantprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("payment.created", "Payment Created"),
                            ("payment.authorized", "Payment Authorized"),
                            ("payment.captured", "Payment Captured"),
                            ("payment.failed", "Payment Failed"),
                            ("payment.voided", "Payment Voided"),
                            ("payment.settled", "Payment Settled"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payment_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PAYMENT_CREATED", "Payment Created"),
                            ("PAYMENT_AUTHORIZED", "Payment Authorized"),
                            ("PAYMENT_CAPTURED", "Payment Captured"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PAYMENT_VOIDED", "Payment Voided"),
                            ("PAYMENT_SETTLED", "Payment Settled"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("AUTHORIZED", "Authorized"),
                            ("CAPTURED", "Captured"),
                            ("SETTLED", "Settled"),
                            ("FAILED", "Failed"),
                            ("VOIDED", "Voided"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payment_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["merchant", "status", "created_at"],
                name="payments_merchan_c85f52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="payments_order_i_3d4604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["customer", "status"], name="payments_custome_04132e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway", "gateway_transaction_id"],
                name="payments_gateway_170425_idx",
            ),
        ),
    ]
