# Generated by Django 5.0.7 on 2026-08-01 11:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("merchant", "0001_initial"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(db_index=True, default="INR", max_length=3),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=50)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "gateway_refund_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("requested_by", models.CharField(blank=True, max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="customer.customerprofile",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="merchant.merchantprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "db_table": "refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeadLetterRefundTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("error_message", models.TextField()),
                ("retry_count", models.IntegerField(default=0)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlq_records",
                        to="refunds.refund",
                    ),
                ),
            ],
            options={
                "db_table": "refund_dead_letter_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("refund.created", "Refund Created"),
                            ("refund.processing", "Refund Processing"),
                            ("refund.succeeded", "Refund Succeeded"),
                            ("refund.failed", "Refund Failed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="refunds.refund",
                    ),
                ),
            ],
            options={
                "db_table": "refund_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("REFUND_CREATED", "Refund Created"),
                            ("REFUND_PROCESSING", "Refund Processing"),
                            ("REFUND_SUCCESS", "Refund Success"),
                            ("REFUND_FAILED", "Refund Failed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="refunds.refund",
                    ),
                ),
            ],
            options={
                "db_table": "refund_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["merchant", "status", "created_at"],
                name="refunds_merchan_ad2653_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["payment", "status"], name="refunds_payment_908281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["customer", "status"], name="refunds_custome_61f9c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["gateway_refund_id"], name="refunds_gateway_6faa77_idx"
            ),
        ),
    ]
