# Generated by Django 5.0.7 on 2026-08-01 11:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="merchant.merchantprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
                "db_table": "customer_profiles",
                "ordering": ["-created_at"],
                "unique_together": {("merchant", "email")},
            },
        ),
        migrations.CreateModel(
            name="SavedPaymentMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CARD", "Card"),
                            ("UPI", "UPI"),
                            ("WALLET", "Wallet"),
                        ],
                        default="CARD",
                        max_length=20,
                    ),
                ),
                (
                    "card_token",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("masked_card_number", models.CharField(blank=True, max_length=30)),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VISA", "Visa"),
                            ("MASTERCARD", "MasterCard"),
                            ("RUPAY", "RuPay"),
                            ("AMEX", "American Express"),
                        ],
                        default="VISA",
                        max_length=20,
                    ),
                ),
                ("exp_month", models.IntegerField(blank=True, null=True)),
                ("exp_year", models.IntegerField(blank=True, null=True)),
                ("fingerprint", models.CharField(blank=True, max_length=128)),
                ("upi_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wallet_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="customer.customerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "customer_saved_payment_methods",
                "ordering": ["-created_at"],
            },
        ),
    ]
