# Generated by Django 5.0.7 on 2026-08-01 11:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("recipient", models.CharField(db_index=True, max_length=255)),
                (
                    "recipient_type",
                    models.CharField(db_index=True, default="CUSTOMER", max_length=20),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("IN_APP", "In-App"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                            ("WEBHOOK", "Webhook"),
                        ],
                        db_index=True,
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("template_name", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_922d15_idx",
                    ),
                    models.Index(
                        fields=["channel", "status"],
                        name="notificatio_channel_411e8e_idx",
                    ),
                ],
            },
        ),
    ]
