# Generated by Django 5.0.7 on 2026-08-01 11:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("MERCHANT", "Merchant"),
                            ("CUSTOMER", "Customer"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=50)),
                ("resource_id", models.CharField(db_index=True, max_length=100)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=100)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                    models.Index(
                        fields=["actor_type", "actor_id"],
                        name="audit_logs_actor_t_3f370f_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="audit_logs_event_t_1d94d4_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="audit_logs_request_298ea7_idx"
                    ),
                ],
            },
        ),
    ]
